package com.nhnent.rookie.NHNGuestBook.model;

/*
// SELECT
SELECT
	[no],
	email,
	[password],
	body,
	regtime,
	modtime
FROM
	articles
WHERE
	[no] = #[no]#
	AND email = #email#
	AND [password] = #[password]#
	AND body = #body#
	AND regtime = #regtime#
	AND modtime = #modtime#

// INSERT
INSERT INTO articles
(
	[no],
	email,
	[password],
	body,
	regtime,
	modtime
)
VALUES
(
	#[no]#,
	#email#,
	#[password]#,
	#body#,
	#regtime#,
	#modtime#
)

// UPDATE
UPDATE
	articles
SET
	[no] = #[no]#,
	email = #email#,
	[password] = #[password]#,
	body = #body#,
	regtime = #regtime#,
	modtime = #modtime#
WHERE
	[no] = #[no]#
	AND email = #email#
	AND [password] = #[password]#
	AND body = #body#
	AND regtime = #regtime#
	AND modtime = #modtime#

// DELETE
DELETE FROM
	articles
WHERE
	[no] = #[no]#
	AND email = #email#
	AND [password] = #[password]#
	AND body = #body#
	AND regtime = #regtime#
	AND modtime = #modtime#

// CREATE
CREATE TABLE articles 
(
	[no] BIGINT AUTO_INCREMENT(1, 1)NOT NULL, 
	email CHARACTER VARYING(255), 
	[password] CHARACTER VARYING(255), 
	body CHARACTER VARYING(1073741823), 
	regtime TIMESTAMP, 
	modtime TIMESTAMP, 
	CONSTRAINT pk_guestbook_no PRIMARY KEY([no])
)
	COLLATE utf8_bin 
	REUSE_OID;
*/
import java.io.Serializable;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;

/**
 * Table name : articles
 * Generated by CUBRID Tools.
 */
public class Article implements Serializable {
	private static final long serialVersionUID = 1L;
	private Long no = null;
	private String email = null;
	private String password = null;
	private String body = null;
	private Timestamp regtime = null;
	private Timestamp modtime = null;

	/**
	 * no (bigint)
	 *
	 * @return no
	 */
	public Long getNo() {
		return no;
	}

	/**
	 * no (bigint)
	 *
	 * @param no
	 */
	public void setNo(Long no) {
		this.no = no;
	}

	/**
	 * email (character varying)
	 *
	 * @return email
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * email (character varying)
	 *
	 * @param email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * password (character varying)
	 *
	 * @return password
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * password (character varying)
	 *
	 * @param password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * body (character varying)
	 *
	 * @return body
	 */
	public String getBody() {
		return body;
	}

	/**
	 * body (character varying)
	 *
	 * @param body
	 */
	public void setBody(String body) {
		this.body = body;
	}

	/**
	 * regtime (timestamp)
	 *
	 * @return regtime
	 */
	public String getRegtime() {
		SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		return ft.format(regtime);
	}

	/**
	 * regtime (timestamp)
	 *
	 * @param regtime
	 */
	public void setRegtime(Timestamp regtime) {
		this.regtime = regtime;
	}

	/**
	 * modtime (timestamp)
	 *
	 * @return modtime
	 */
	public String getModtime() {
		SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		return ft.format(regtime);
	}

	/**
	 * modtime (timestamp)
	 *
	 * @param modtime
	 */
	public void setModtime(Timestamp modtime) {
		this.modtime = modtime;
	}

}
