package com.nhnent.rookie.NHNGuestBook.model;

/*
// SELECT
SELECT
	[no],
	email,
	[password],
	body,
	regtime,
	modtime
FROM
	articles
WHERE
	[no] = #[no]#
	AND email = #email#
	AND [password] = #[password]#
	AND body = #body#
	AND regtime = #regtime#
	AND modtime = #modtime#

// INSERT
INSERT INTO articles
(
	[no],
	email,
	[password],
	body,
	regtime,
	modtime
)
VALUES
(
	#[no]#,
	#email#,
	#[password]#,
	#body#,
	#regtime#,
	#modtime#
)

// UPDATE
UPDATE
	articles
SET
	[no] = #[no]#,
	email = #email#,
	[password] = #[password]#,
	body = #body#,
	regtime = #regtime#,
	modtime = #modtime#
WHERE
	[no] = #[no]#
	AND email = #email#
	AND [password] = #[password]#
	AND body = #body#
	AND regtime = #regtime#
	AND modtime = #modtime#

// DELETE
DELETE FROM
	articles
WHERE
	[no] = #[no]#
	AND email = #email#
	AND [password] = #[password]#
	AND body = #body#
	AND regtime = #regtime#
	AND modtime = #modtime#

*/
import java.util.Date;

/**
 * Table name : articles
 * Generated by CUBRID Tools.
 */
public class ArticleModel {
	private Long no = null;
	private String email = null;
	private String password = null;
	private String body = null;
	private Date regtime = null;
	private Date modtime = null;

	/**
	 * no (bigint)
	 *
	 * @return no
	 */
	public Long getNo() {
		return no;
	}

	/**
	 * no (bigint)
	 *
	 * @param no
	 */
	public void setNo(Long no) {
		this.no = no;
	}

	/**
	 * email (character varying)
	 *
	 * @return email
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * email (character varying)
	 *
	 * @param email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * password (character varying)
	 *
	 * @return password
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * password (character varying)
	 *
	 * @param password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * body (character varying)
	 *
	 * @return body
	 */
	public String getBody() {
		return body;
	}

	/**
	 * body (character varying)
	 *
	 * @param body
	 */
	public void setBody(String body) {
		this.body = body;
	}

	/**
	 * regtime (timestamp)
	 *
	 * @return regtime
	 */
	public Date getRegtime() {
		return regtime;
	}

	/**
	 * regtime (timestamp)
	 *
	 * @param regtime
	 */
	public void setRegtime(Date regtime) {
		this.regtime = regtime;
	}

	/**
	 * modtime (timestamp)
	 *
	 * @return modtime
	 */
	public Date getModtime() {
		return modtime;
	}

	/**
	 * modtime (timestamp)
	 *
	 * @param modtime
	 */
	public void setModtime(Date modtime) {
		this.modtime = modtime;
	}

}
